### ISSUE TITLE
Please 

### ISSUE THREAD

**Issue by Sergiocubano1** [FlowerWorks/Apodidae#25]
Mt6985 add please 🙏🙏

**Comment by naranyinyun** [comment]
The MT6985 had been supported.

**Comment by Sergiocubano1** [comment]
> The MT6985 had been supported.

It does not allow the module to be inserted because an error appears saying model not supported

**Comment by Sergiocubano1** [comment]
> The MT6985 had been supported.

![Screenshot_2024-03-21-18-25-34-771_io github huskydg magisk](https://github.com/FlowerWorks/Apodidae/assets/48456116/70fa4d1b-1602-4c2b-a72b-bf12ab1f7950)

**Comment by Sergiocubano1** [comment]
That's now in the latest update 😞😞

**Comment by naranyinyun** [comment]
Sorry for hearing that.

In fact, the Magisk Module of Apodidae can be said that has unsupported, but because of the workflows it's not be removed right now.

It's a better choice to use the Cutoolbox, or you cloud replace the bin in [module](https://github.com/chenzyadb/CuprumTurbo-Scheduler/tree/main/magisk).

Actually, I have very little time to maintain it.
